### PR TITLE
Add support for M5StickC Plus2

### PR DESCRIPTION
**Pull request by smart40-githib**

### CODE REVIEW

**Comment by raomin** [comment]
Thanks @smart40-githib, looks good. Did you check retro compatibility with M5StickC?

**Comment by smart40-githib** [comment]
Unfortunately I only have a Plus2. The changes are mainly to use the appropriate header files when configured for the Plus2 and to replace some unsupported or deprecated calls with the M5Unified equivalents. It should be backwards compatible.

From the issues page I can see that I may have to make a small change so please hold off for now.

**Comment by smart40-githib** [comment]
The fix has been confirmed good in the issues topic, the pull request is good to go.

**Comment by raomin** [comment]
Hmm M5 libs previous plus2 has no `M5.Display`. 
Your code breaks for the other env. 
Is `M5.Axp.ScreenBreath(12);` not working on M5StickC Plus2

**Comment by raomin** [comment]
... ah, it doesn't exist on M5Stickc Plus2.
I'll make it conditional then...

**Pull request merged**
