### PR TITLE
Fix serial write API to make sure all bytes are transmitted

### PR DESCRIPTION
**Pull request by abutscher**
We need to use the serial write API where the amount of bytes to be sent can be
chosen. That way, commands that contain a 0 byte are transmitted correctly.

When using the old API, the array that shall be sent is interpreted as a
C string. Therefore, any byte before a 0 byte in the array is seen as the last
byte to be sent.

Actual bug:
When querying register 0 from the heat pump, the third byte in the packet to be
sent is a 0 byte. Therefore, only the first two bytes (which are preceeding the
0 byte) are actually sent. The register ID (which is 0) and the two CRC bytes
are skipped.
The heat pump answers with 0x15 0xea which more or less means "query not
understood".

### CODE REVIEW

**Comment by raomin** [comment]
Hi @abutscher,
You have definitely something here...! registry 0 and (rare) cases where CRC would be 0x0 will fail...
Sizeof will return 5 and send the ending 0x00.
I would suggest either to get `prep[]` as `char[4]`
```c++
char prep[] = {0x03, 0x40, regID, 0x00};
...
MySerial.write(prep,sizeof(prep));
```
or
```c++
MySerial.write(prep,4);
```
... or both

**Comment by abutscher** [comment]
Got your point. I clearly overlooked that design issue. Thanks for clarifying.

**Comment by raomin** [comment]
But here you are still missing the write limitation to 4.
When you're passing prep you're passing a pointer to the start of a char[] but it's not passing the size. So prep[5] is uninitialized and is most probably not null. So write() would send from prep[0] until it finds a 0.

Add write(prep, 4) that should do it.

**Comment by abutscher** [comment]
Ahh, it's a pointer! You're right, of course. sizeof with a pointer argument obviously will not work then.

**Review by raomin — APPROVED** [review]
Actually, sizeof would have worked here. I just didn't see it in the latest change! But 4 is fine too. Commands length will always be 4.
Anyway, thanks for that @abutscher !

**Comment by abutscher** [comment]
I just re-read the C specification and came to the same conclusion. To be honest, I was not 100% sure how brace enclosed initialized arrays work with sizeof. Anyway, we got a solution :-). Thank you, too.

**Pull request merged**
