### PR TITLE
Support for NodeMCUv2/ESP-12E/ESP8266 board

### LINKED ISSUE #14: ESP8266 support
Hi, thanks for this great repository!  
Can this work with an ESP8266?  
If yes, can you provide some hint on what needs to be changed please?  
Thanks again,
Andrea

### LINKED ISSUE #65: Possible to use NodeMCU CH340?
Hello,

great project! I want to test if it works for me, too.
I have several NodeMCU CH340. Example: https://www.makershop.de/plattformen/esp8266/nodemcu-esp8266-dev-kit/
I don't have experience with paltformio...
Does the project support NodeMCU?

Build process works fine. But Upload not. Error 2

I tried it with a new empty project with board type NodeMCU 1.0
Build & Upload works fine

Then I tried to add NodeMCU to your project
Create new project - same name, board NodeMCU 1.0
Is this the correct way?
Now Build process stops with message: fatal error: WiFi.h: No such file or directory
Nothing found in the web which really helps me.

Can anybody help?

BTW: I had to change comm.h lien 26 to   MySerial.write(prep);. Otherwise build did not run

Thank you very much!
Andreas

### LINKED ISSUE #71: ESPAltherma on ESP8266
Hallo, 

Can I also use the software on an ESP8266?

Thanks

### PR DESCRIPTION
**Pull request by sh41**
Thanks for such a great project. I didn't have an ESP32, but I did have a spare NodeMCU, so I had a go at getting it working on there. Mine is actually an ESP-12F, but PlatformIO didn't list that one so I've just used it as "[NodeMCU 1.0 (ESP-12E Module)](https://docs.platformio.org/en/stable/boards/espressif8266/nodemcuv2.html)" . This PR is the result. It seems to work OK with my EHBX16CB3V + ERLQ016CAV3. 

Only very basic figures so far, but I'll get on with setting up more over the next few days: 
image

I noted the comments in #14 that using a software serial library might work, so that is what I have done. The only other major change was to abstract out the restart function. 

I also added the build flag `-D_GNU_SOURCE` to stop messages like this appearing: 
image

The only other thing that needs to be changed is dropping the `PROGMEM` part of the `LabelDef` declaration in your chosen definitions file. Otherwise the board won't even boot. 

The only thing that I think could be improved is that you can't connect to the monitor or flash the firmware over USB when the pins are connected to the X10A. Connecting to the monitor first and then connecting the pins to the X10A works fine. 

Also it seems that it can't be powered from the X10A interface so I'm powering direct from USB. 

I hope this is useful to others. I haven't been able to test that it doesn't break the ESP32 or M5StickC setups as I don't have either of those. 

Thanks again for all your efforts on this, it is really useful!

Fixes #14, fixes #65, fixes #71

### CODE REVIEW

**Comment by raomin** [comment]
Ok, it's merged. Thanks @sh41.
Can you PR a change on the Readme for ESP8266 users too?

**Comment by sh41** [comment]
Thanks for merging. I'll work on a PR for the README this week. I've since found that by changing serial pins I can keep the monitor running and can now power the ESP8266 from the X10A interface. I'll write it all up in the README.

**Comment by Matssa56** [comment]
@sh41 hi, i tried to build on a D1 mini based on a esp8266 and it doesn't work, I can build and flash but the program seems in a bootloop. Can you maybe help me out since I don't want to use an ESP32 (crappy wifi)?

**Comment by sh41** [comment]
@Matssa56 try dropping the `PROGMEM` keyword from the file you selected in stage 3 of [step 1](https://github.com/raomin/ESPAltherma#step-1-uploading-the-firmware). Mine looks like this:
```shell
$ head 'include/def/ALTHERMA(LT_CA_CB_11-16KW).h'
#include "labeldef.h"
//  This file is a definition file for the ESPAtherma.
//  uncomment each value you want to query for your installation.

LabelDef labelDefs[] = {
```

I didn't have this in my changelogs and missed adding it to the documentation. Let us know if that works for you and if it does maybe update the docs? Thanks!

**Comment by raomin** [comment]
Why would `PROGMEM` crash esp8266?

**Comment by sh41** [comment]
I never figured out why it was causing problems & to be honest I assumed that I was doing something wrong! I only realised it was causing me problems by trial and error. My ESPAltherma is functions well with out the PROGMEM directive so I never looked into it further.

**Comment by Matssa56** [comment]
> 

Hey,

So I tested what you said and it finally starts! It didn't when I flashed it a first time, I had to flash it several times for it to boot. I didn't plug it in the PAC for now, I'll have to take time tomorrow or afterwards. I'm still gonna test the Wifi strength, see if it is better than the ESP32...

**Comment by Matssa56** [comment]
@sh41 what pins did you use? I'm trying to use RX GPIO 3 and TX GPIO 1 with GPIO 0 for the thermostat relay (even though I don't have one). When connecting to the heat pump, I keep getting some timeouts, just as if the RX and TX pins aren't working.

**Comment by sh41** [comment]
@Matssa56 
From the README:

> For ESP8266 pins 4 & 5 (D2 & D1 on the NodeMCUv2) are known to work well.

**Comment by Matssa56** [comment]
> 

Yeah saw that afterwards... I tried to put RX on 4 and TX on 5 and I get some stuff out, but everything at 0 xD

{
  "*Refrigerant type": "Conv 801 not avail.",
  "Sensor Data Qty": 0,
  "INV compressor Qty": 0,
  "STD compressor Qty": 0,
  "Fan Data Qty": 0,
  "Expansion Valve Data Qty": 0,
  "4 Way Valve Data Qty": 0,
  "Crank Case Heater Qty": 0,
  "Solenoid valve Qty": 0,
  "Max. connectable indoor units": 0,
  "Connected Indoor Unit Qty": 0,
  "O/U MPU ID (xx)": 0,
  "O/U MPU ID (yy)": 0,
  "O/U capacity (kW)": 0,
  "": "Conv 998 not avail.",
  "WifiRSSI": "-77dBm"
}

Looks like the include file isn't the good one :S

**Pull request merged**
