### PR TITLE
Support SG High/Low level trigger relay board

### PR DESCRIPTION
**Pull request by maps2002**
Hi there,

I have a relay board that is triggered by setting the pin signal to low, instead of high.
I adjusted the code to support both high/low relay trigerred boards.

It is working on my side. Are you able to test it, and merge it (maybe a squash and merge) if you think this is acceptable?

Thank you for your effort.

### CODE REVIEW

**Comment by andreapier** [comment]
Hi @maps2002, let me first clearly state that this is solely my opinion, and I do not intend to influence @raomin final judgement at all.
When I first coded the SG integration, I considered this approach and also implemented it (even if it was not as good as yours).
Later I discarded this implementation, as I thought it could introduces some subtle risks for the average user.
Doesn't using a low level trigger relay means that unplugging your ESP32/power source will close SG contacts (hence your heat pump will enter the SG3 state)?

**Comment by maps2002** [comment]
Hi @andreapier ,

I am not an electronics/electrical expert, but I don't think so.
It seems the circuit will be in a "open state" (neither low or high).

Could you take a look at these kind of posts/information and tell me what you think?
https://forum.arduino.cc/t/question-about-low-level-triggered-relay/911115/7

Thank you

**Comment by andreapier** [comment]
@maps2002 I did some more testing with an unplugged relay board. Your findings seem to be correct. NO contacts stay open if there is no power. I will test it a bit more in the next days and let you know.
Btw, thanks for the link.

**Comment by raomin** [comment]
Looks good to me! Thanks @maps2002 (and @andreapier)

**Pull request merged**
